const EN_RU: [string, string][] = [
  ['body-focused repetitive behaviors', 'привычки тела'],
  ['Body-Focused Repetitive Behaviors', 'привычки тела'],
  ['hyperfunctional / muscle tension dysphonia', 'напряжённый голос'],
  ['tooth contact / bracing', 'контакт зубов без еды'],
  ['bracing/thrusting', 'упор челюсти'],
  ['Cheilophagia / BFRB', 'прикус губ'],
  ['Sleep / awake bruxism', 'скрежет зубами'],
  ['Excoriation / skin picking', 'расчёсывание кожи'],
  ['tonic/collapsed immobility', 'обмякание'],
  ['collapsed immobility', 'обмякание'],
  ['Collapsed immobility', 'Обмякание'],
  ['globus hystericus', 'ком в горле'],
  ['Globus pharyngeus', 'ком в горле'],
  ['sighing respiration', 'частое вздыхание'],
  ['Habit reversal', 'смена привычки'],
  ['habit reversal', 'смена привычки'],
  ['Response-focused', 'Сдерживание'],
  ['response-focused', 'сдерживание'],
  ['expressive suppression', 'сдерживание чувства'],
  ['Emotional eating', 'еда от тревоги'],
  ['emotional eating', 'еда от тревоги'],
  ['emotional eaters', 'тех, кто заедает тревогу'],
  ['restrained eaters', 'тех, кто жёстко держит еду'],
  ['defense cascade', 'защитный ряд'],
  ['Defense cascade', 'Защитный ряд'],
  ['fight/flight', 'бой или бегство'],
  ['safety behavior', 'жест безопасности'],
  ['Safety behavior', 'жест безопасности'],
  ['body checking', 'проверка тела'],
  ['skin picking', 'расчёсывание кожи'],
  ['Hair twirling', 'кручение волос'],
  ['knuckle cracking', 'хруст суставов'],
  ['Awake bruxism', 'стискивание челюсти наяву'],
  ['Sleep bruxism', 'скрежет во сне'],
  ['Cheilophagia', 'прикус губ'],
  ['cheilophagia', 'прикус губ'],
  ['Onychophagia', 'грызение ногтей'],
  ['onychophagia', 'грызение ногтей'],
  ['onychotillomania', 'теребление ногтей'],
  ['Cauda equina', 'конский хвост'],
  ['Lobbezoo и соавт. (2018)', 'консенсус 2018 года'],
  ['Lobbezoo и соавт.', 'консенсус'],
  ['Kozlowska и соавт. (2015)', 'обзор 2015 года'],
  ['Kozlowska и соавт.', 'обзор'],
  ['Kozlowska, 2015', 'обзор 2015 года'],
  ['Lee и Lipner (2022)', 'обзор 2022 года'],
  ['Lee, Lipner, 2022', 'обзор 2022 года'],
  ['Lee и Lipner', 'обзор'],
  ['Lee и Kim (2012)', 'обзор 2012 года'],
  ['Lee и Kim', 'обзор'],
  ['Morin и Benca (2012)', 'обзор сна 2012 года'],
  ['Morin, Benca, 2012', 'обзор сна 2012 года'],
  ['Morin и Benca', 'обзор сна'],
  ['Morin, Benca', 'обзор сна'],
  ['Gross (2002)', 'работа 2002 года'],
  ['Gross, 2002', 'работа 2002 года'],
  ['Chang и соавт.', 'исследование света'],
  ['Azrin и соавт.', 'испытание'],
  ['Malcomson (1968)', 'работа 1968 года'],
  ['Malcomson', 'обзор'],
  ['Abramowitz', 'обзор'],
  ['Kozlowska', 'обзор'],
  ['Lobbezoo', 'консенсус'],
  ['Lipner', 'обзор'],
  ['Benca', 'обзор сна'],
  ['Morin', 'обзор сна'],
  ['Macht', 'обзор еды'],
  ['Gross', 'работа'],
  ['Taylor', 'обзор'],
  ['McKay', 'обзор'],
  ['Chang', 'исследование'],
  ['Azrin', 'испытание'],
  ['fragmentация', 'дробление'],
  ['fragmentaция', 'дробление'],
  ['fragmentation', 'дробление'],
  ['ICHD-3', 'классификация головной боли'],
  ['ICHD', 'классификация головной боли'],
  ['CBT-I', 'поведенческая работа со сном'],
  ['CBT', 'поведенческая работа'],
  ['BFRB-', 'привычки тела '],
  ['BFRB', 'привычки тела'],
  ['DSM-5', 'классификация'],
  ['TTH', 'боль напряжения'],
  ['SCM', 'кивательной мышцы'],
  ['LPR', 'заброс в горло'],
  ['PNAS', 'журнал'],
  ['PAG', 'ядра мозга'],
  ['EMG', 'запись мышц'],
  ['Lancet', 'обзор'],
  ['eReaders', 'экран'],
  ['eReader', 'экран'],
  ['Guarding', 'Зажим'],
  ['guarding', 'зажим'],
  ['Checking', 'Проверка'],
  ['checking', 'проверка'],
  ['Fidgeting', 'Ёрзание'],
  ['fidgeting', 'ёрзание'],
  ['Suppression', 'Сдерживание'],
  ['suppression', 'сдерживание'],
  ['Arousal', 'Возбуждение'],
  ['arousal', 'возбуждение'],
  ['Freeze', 'Замирание'],
  ['freeze', 'замирание'],
  ['Flight', 'Бегство'],
  ['flight', 'бегство'],
  ['Fight', 'Бой'],
  ['fight', 'бой'],
  ['Sleep', 'Сон'],
  ['sleep', 'сон'],
  ['Awake', 'Наяву'],
  ['awake', 'наяву'],
  ['bruxism', 'скрежет зубами'],
  ['globus', 'ком в горле'],
  ['spasm', 'спазм'],
  ['urge', 'напряжение'],
  ['bracing', 'зажим'],
  ['continuum', 'ряд'],
  ['habituation', 'привыкание'],
  ['concealment', 'сокрытие'],
  ['reappraisal', 'переоценка'],
  ['insomnia', 'бессонница'],
  ['behavior', 'поведение'],
  ['behaviors', 'привычки'],
]

export function ruOnly(text: string) {
  let t = text
  for (const [en, ru] of EN_RU) t = t.replaceAll(en, ru)
  t = t
    .replace(/[A-Za-zА-Яа-яЁё-]*[A-Za-z][A-Za-zА-Яа-яЁё-]*/g, '')
    .replace(/[A-Za-z][A-Za-z0-9'’./_-]*/g, '')
    .replace(/\(\s*\)/g, '')
    .replace(/\s{2,}/g, ' ')
    .replace(/\s+([,.;:!?])/g, '$1')
    .replace(/^[\s/·–—-]+/, '')
    .trim()
  return t
    .replace(/^\p{Ll}/u, (ch) => ch.toLocaleUpperCase('ru'))
    .replace(/\.\s+(\p{Ll})/gu, (_, ch: string) => `. ${ch.toLocaleUpperCase('ru')}`)
}

export function ruList(items: string[] | undefined) {
  return (items ?? []).map(ruOnly).filter(Boolean)
}
